apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: website-{{template "fullname" .}}
  {{- if .Values.global.tls}}
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$request_uri
    ingress.kubernetes.io/auth-url: http://oauth2-proxy.kube-system.svc.cluster.local:4180/oauth2/auth
  {{- end}}
spec:
  {{- if .Values.global.tls}}
  tls:
    - hosts:
        - {{.Values.global.domains.website}}
      secretName: dev-tls
  {{- end}}
  rules:
  - host: {{.Values.global.domains.website}}
    http:
      paths:
      - path: /api/content
        backend:
          serviceName: api-content
          servicePort: 80
      - path: /api/contact-mailer
        backend:
          serviceName: contact-mailer
          servicePort: 80
      - path: /api/schedule
        backend:
          serviceName: api-scheduling
          servicePort: 8081
      - backend:
          serviceName: frontend
          servicePort: 80
