apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: retrace
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: 
          - -addr=:80
          - "-sender-email={{.Values.email.from}}"
        env:
          - name: BUSINESS_EMAIL_TO
            value: {{.Values.email.to.business}}
          - name: CAREER_EMAIL_TO
            value: {{.Values.email.to.career}}
          - name: SMTP_HOST
            value: {{.Values.global.smtp.host}}
          - name: SMTP_PORT
            value: "{{.Values.global.smtp.port}}"
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef: {name: {{ template "fullname" . }}, key: username}
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef: {name: {{ template "fullname" . }}, key: password}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
