apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.db.host }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: mysql
    port: {{.Values.global.db.port}}
    targetPort: mysql
  selector:
    app: {{ template "fullname" . }}
