# Default values for ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/google_containers/nginx-ingress-controller
  tag: 0.9.0-beta.3
  pullPolicy: IfNotPresent
defaultBackendImage:
  repository: gcr.io/google_containers/defaultbackend
  tag: "1.0"
service:
  name: ingress-controller
  type: NodePort
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

