# Default values for contact-mailer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: retrace/contact-mailer
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: contact-mailer
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# turn on/off prometheus scraping annotation
prometheus: true

email:
  from: scheduling-sandbox@retracehealth.com
  to:
    business: piedpiper@retracehealth.com
    career: piedpiper@retracehealth.com

# SMTP server details
smtp:
  server: email-smtp.us-east-1.amazonaws.com
  port: 587
  username: ""
  password: ""
