apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: retrace
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPort }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "kill -QUIT 1; while kill -0 1; do sleep 1; done"]
        resources:
{{ toYaml .Values.resources | indent 12 }}
