apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  zoomKey:  {{.Values.key | b64enc | quote}}
  zoomSecret: {{.Values.secret | b64enc | quote}}
