# Default values for api-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: retrace/api-authorization
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

javaOpts: -Xmx64m -Xms64m

global:
  springProfile: dev

  db:
    host: localhost
    port: 3306
    user: root
    pass: ""

jwtSecret: RETRACE-HEALTH-JWT-SIGNING-KEY-2016
dbName: authorizations
clientSecrets:
  scheduling: password
  account: password
  notification: password
  taskSched: password
