apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: retrace
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: LOG_SUFFIX
          value: -json
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.global.springProfile | quote}}
        - name: JAVA_OPTS
          value: {{.Values.javaOpts | quote}}
        - name: API_NOTIFICATION_FROM_EMAIL_ADDR
          value: {{.Values.email.from}}
        - name: NOTIFICATION_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef: {name: {{template "fullname" .}}, key: clientSecret}
        - name: STMP_SERVER_USER
          valueFrom:
            secretKeyRef: {name: {{template "fullname" .}}, key: smtpUser}
        - name: STMP_SERVER_PASSWORD
          valueFrom:
            secretKeyRef: {name: {{template "fullname" .}}, key: smtpPass}
        - name: STMP_SERVER
          value: {{.Values.global.smtp.host | quote}}
        - name: STMP_PORT
          value: {{.Values.global.smtp.port | quote}}
  
        readinessProbe: {httpGet: {port: {{.Values.service.internalPort}}, path: /health}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
