apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  smtpUser: {{.Values.global.smtp.user | b64enc | quote}}
  smtpPass: {{.Values.global.smtp.pass | b64enc | quote}}
  clientSecret: {{.Values.clientSecret | b64enc | quote}}
