apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: 5601
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
