apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: retrace
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}{{ .Values.image.version }}"
        args: [ "-addr=:{{.Values.service.internalPort}}", "-json" ]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: clientSecret
          - name: DB_CONNECT
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: dbConnect
        ports:
          - containerPort: {{.Values.service.internalPort}}
        readinessProbe: {httpGet: {port: {{.Values.service.internalPort}}, path: /health}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
