
api-account: {image: {version: ":latest"}}
api-audit: {image: {version: ":latest"}}
api-authorization: {image: {version: ":latest"}}
api-content: {image: {version: ":latest"}}
api-google: {image: {version: ":latest"}}
api-notification: {image: {version: ":latest"}}
api-scheduling: {image: {version: ":latest"}}
api-zoom: {image: {version: ":latest"}}
contact-mailer: {image: {version: ":latest"}}
frontend: {image: {version: ":latest"}}
task-scheduler: {image: {version: ":latest"}}
