# Default values for api-content.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: retrace/api-content
pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

global:
  db:
    host: localhost
    port: 3306
    user: root
    pass: ""

dbName: content
