# Default values for api-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: retrace/api-account
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 6000
  internalPort: 6000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

javaOpts: -Xmx64m -Xms64m

global:
  springProfile: dev

  db:
    host: localhost
    port: 3306
    user: root
    pass: ""

dbName: accounts

clientSecret: password
