apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  cookieSecret: {{ .Values.auth.cookieSecret | b64enc | quote }}
  googleClientId: {{ .Values.auth.googleClientId | b64enc | quote }}
  googleClientSecret: {{ .Values.auth.googleClientSecret | b64enc | quote }}
