apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  dbConnect:  {{ printf "jdbc:mysql://%s:%0.0f/%s%s" .Values.global.db.host .Values.global.db.port .Values.dbName .Values.global.db.javaParams | b64enc | quote}}
  dbUser: {{.Values.global.db.user | b64enc | quote}}
  dbPass: {{.Values.global.db.pass | b64enc | quote}}
  notificationSecret: {{.Values.clientSecrets.notification | b64enc | quote}}
  schedulingSecret: {{.Values.clientSecrets.scheduling | b64enc | quote}}
  accountSecret: {{.Values.clientSecrets.account | b64enc | quote}}
  taskSchedSecret: {{.Values.clientSecrets.taskSched | b64enc | quote}}
  jwtSecret: {{.Values.jwtSecret | b64enc | quote}}
