apiVersion: v1
kind: Secret
metadata:
  name: retrace
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{.Values.dockerCredentials | b64enc | quote}}
