# Default values for oauth-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.io/colemickens/oauth2_proxy
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: oauth2
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

auth:
  cookieSecret: ""
  googleClientId: ""
  googleClientSecret: ""
