# Default values for api-account.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: retrace/api-scheduling
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

javaOpts: -Xmx64m -Xms64m

global:
  springProfile: dev

  db:
    host: localhost
    port: 3306
    user: root
    pass: ""

dbName: scheduledb
clientSecret: password
