apiVersion: v1
kind: Service
metadata:
  name: default-http-backend-{{template "fullname" .}}
  namespace: kube-system
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
