apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.{{.Release.Namespace}}"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
        volumeMounts:
        - name: mnt
          mountPath: /mnt
          readOnly: true
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mnt
        hostPath:
          path: /mnt
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
