apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring-{{template "fullname" .}}
  annotations:
    {{- if .Values.global.tls}}
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$request_uri
    ingress.kubernetes.io/auth-url: http://oauth2-proxy.kube-system.svc.cluster.local:4180/oauth2/auth
    {{- end}}
    ingress.kubernetes.io/rewrite-target: /
spec:
  {{- if .Values.global.tls}}
  tls:
    - hosts:
        - {{.Values.global.domains.monitoring}}
      secretName: monitoring-tls
  {{- end}}
  rules:
  - host: {{.Values.global.domains.monitoring}}
    http:
      paths:
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 80
      - path: /prometheus
        backend:
          serviceName: prometheus
          servicePort: 80
      - path: /kibana
        backend:
          serviceName: kibana
          servicePort: 80
