apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-smtp" .Release.Name .Chart.Name }}
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  username: {{ .Values.smtpUsername | b64enc | quote }}
  password: {{ .Values.smtpPassword | b64enc | quote }}
