apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  dbConnect: {{printf "%s:%s@tcp(%s:%0.0f)/%s" .Values.global.db.user .Values.global.db.pass .Values.global.db.host .Values.global.db.port .Values.dbName | b64enc | quote }}
