apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      imagePullSecrets:
        - name: retrace
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.name }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: LOG_SUFFIX
          value: -json
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.global.springProfile | quote}}
        - name: JAVA_OPTS
          value: {{.Values.javaOpts | quote}}
        - name: API_AUDIT_DB_CONNECT
          valueFrom:
            secretKeyRef: {name: {{ template "fullname" . }}, key: dbConnect}
        - name: API_AUDIT_DB_USER
          valueFrom:
            secretKeyRef: {name: {{ template "fullname" . }}, key: dbUser}
        - name: API_AUDIT_DB_PASSWORD
          valueFrom:
            secretKeyRef: {name: {{ template "fullname" . }}, key: dbPass}
        readinessProbe: {httpGet: {port: {{.Values.service.internalPort}}, path: /health}}
        resources:
{{ toYaml .Values.resources | indent 12 }}
